name       : libvte
version    : 0.44.2
release    : 14
source     :
    - http://ftp.gnome.org/pub/gnome/sources/vte/0.44/vte-0.44.2.tar.xz : a1ea594814bb136a3a9a6c7656b46240571f6a198825c1111007fe99194b0949
license    : GPL-2.0+
summary    : The VTE package contains a termcap file implementation for terminal emulators.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gnutls)
    - vala
    - gperf
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
setup      : |
    %configure --disable-static \
               --enable-introspection \
               --libexecdir=%libdir%/vte
build      : |
    %make
install    : |
    %make_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
