name       : libvte
version    : 0.70.0
release    : 50
source     :
    - https://download.gnome.org/sources/vte/0.70/vte-0.70.0.tar.xz : 93e0dd4a1bc2a7a1a62da64160a274cce456976ea1567d98591da96e2d265ae6
license    : GPL-2.0-or-later
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(libpcre2-8)
    - gperf
    - gi-docgen
    - libiconv-devel
    - vala
rundeps    :
    - devel :
        - pcre2-devel
patterns   :
    - docs :
        - /usr/share/doc/*
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-build-Add-no-exceptions-sanity-check.patch
    %patch -p1 < $pkgfiles/vte291-cntnr-precmd-preexec-scroll.patch
    %meson_configure -Ddocs=true -Dgtk4=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
