name       : libvte
version    : 0.52.2
release    : 23
source     :
    - https://download.gnome.org/sources/vte/0.52/vte-0.52.2.tar.xz : 0f2657cef52accbfe56feede553155552d7c1984b1291838af3cb8cfc19b26af
license    : GPL-2.0-or-later
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre2-8)
    - gperf
    - vala
setup      : |
    # From Fedora
    %patch -p1 < $pkgfiles/vte291-command-notify-scroll-speed.patch
    autoreconf -vfi
    %configure --disable-static \
               --enable-introspection \
               --libexecdir=%libdir%/vte
build      : |
    %make
install    : |
    %make_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
