name       : libvte
version    : 0.52.1
release    : 22
source     :
    - https://download.gnome.org/sources/vte/0.52/vte-0.52.1.tar.xz : b0fd4c34905adcb77a1c8a2e4fc1677c79f1115aaea49705b9c8976523386ad3
license    : GPL-2.0-or-later
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre2-8)
    - gperf
    - vala
setup      : |
    # From Fedora
    %patch -p1 < $pkgfiles/vte291-command-notify-scroll-speed.patch
    autoreconf -vfi
    %configure --disable-static \
               --enable-introspection \
               --libexecdir=%libdir%/vte
build      : |
    %make
install    : |
    %make_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
