name        : libvte
version     : 0.42.5
release     : 13
source     :
    - http://ftp.gnome.org/pub/gnome/sources/vte/0.42/vte-0.42.5.tar.xz : 53cc15c5315d73b69f7848e07a5c512cd40b7caf0323e3d0e0d75d7ae65deee7
license     : GPL-2.0+
summary     : The VTE package contains a termcap file implementation for terminal emulators.
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gnutls)
    - vala
    - gperf
description : |
    The VTE package contains a termcap file implementation for terminal emulators.
setup      : |
    %patch -p1 < $pkgfiles/vte291-command-notify.patch
    autoreconf -vfi
    %configure --disable-static \
               --enable-introspection \
               --libexecdir=/usr/lib/vte
build      : |
    %make
install    : |
    %make_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
