name       : libvte
version    : 0.46.1
release    : 16
source     :
    - http://ftp.gnome.org/pub/gnome/sources/vte/0.46/vte-0.46.1.tar.xz : 8800cf8bc259704a12ad1853fb0eb43bfe3857af15242e6fb9f2c3fd95b3f5c6
license    : GPL-2.0+
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre2-8)
    - pkgconfig(gnutls)
    - vala
    - gperf
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
setup      : |
    # From Fedora
    %patch -p1 < $pkgfiles/vte291-command-notify-scroll-speed.patch
    autoreconf -vfi
    %configure --disable-static \
               --enable-introspection \
               --libexecdir=%libdir%/vte
build      : |
    %make
install    : |
    %make_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
