name       : libvte
version    : 0.58.2
release    : 28
source     :
    - https://download.gnome.org/sources/vte/0.58/vte-0.58.2.tar.xz : 33c966d2b1f2c3b0f9416dbca883fd746159b5bd040350e3b78f8104b2a42bc0
license    : GPL-2.0-or-later
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre2-8)
    - gperf
    - gtk-doc
    - libiconv-devel
    - vala
rundeps    :
    - devel :
        - pcre2-devel
setup      : |
    %patch -p1 < $pkgfiles/vte291-cntnr-precmd-preexec-scroll.patch
    %meson_configure -Ddocs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
