name       : libvte
version    : 0.72.2
release    : 55
source     :
    - https://download.gnome.org/sources/vte/0.72/vte-0.72.2.tar.xz : f7966fd185a6981f53964162b71cfef7e606495155d6f5827b72aa0dd6741c9e
license    : GPL-2.0-or-later
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(libpcre2-8)
    - gperf
    - gi-docgen
    - libiconv-devel
    - vala
rundeps    :
    - devel :
        - pcre2-devel
patterns   :
    - docs :
        - /usr/share/doc/*
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-build-Add-no-exceptions-sanity-check.patch
    %patch -p1 < $pkgfiles/vte291-cntnr-precmd-preexec-scroll.patch
    %meson_configure -Ddocs=true -Dgtk4=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
