name       : libvte
version    : 0.62.2
release    : 36
source     :
    - https://download.gnome.org/sources/vte/0.62/vte-0.62.2.tar.xz : b0300bbcf0c02df5812a10a3cb8e4fff723bab92c08c97a0a90c167cf543aff0
license    : GPL-2.0-or-later
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre2-8)
    - gperf
    - gtk-doc
    - libiconv-devel
    - vala
rundeps    :
    - devel :
        - pcre2-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-build-Add-no-exceptions-sanity-check.patch
    %patch -p1 < $pkgfiles/vte291-cntnr-precmd-preexec-scroll.patch
    %patch -p1 < $pkgfiles/Revert-lib-Sanitize-the-passed-in-font-description.patch
    %meson_configure -Ddocs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
