name       : libvte
version    : 0.56.2
release    : 24
source     :
    - https://download.gnome.org/sources/vte/0.56/vte-0.56.2.tar.xz : 6e95357098752848c78892b00c434b5c63c7a7f0db7425773be3aabf7013d237
license    : GPL-2.0-or-later
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre2-8)
    - gperf
    - vala
setup      : |
    # From Fedora
    %patch -p1 < $pkgfiles/vte291-command-notify-scroll-speed.patch
    autoreconf -vfi
    %configure --disable-static \
               --enable-introspection \
               --libexecdir=%libdir%/vte
build      : |
    %make
install    : |
    %make_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
