name       : libvte
version    : 0.49.1
release    : 19
source     :
    - https://download.gnome.org/sources/vte/0.49/vte-0.49.1.tar.xz : 6d5c2b6c5a953f10167ce3e2ee0e7b3f8a56aafc7a1c2e1509d1a0afb7f4bc29
license    : GPL-2.0+
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre2-8)
    - gperf
    - vala
setup      : |
    # From Fedora
    %patch -p1 < $pkgfiles/vte291-command-notify-scroll-speed.patch
    autoreconf -vfi
    %configure --disable-static \
               --enable-introspection \
               --libexecdir=%libdir%/vte
build      : |
    %make
install    : |
    %make_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
