name       : libvte
version    : '0.60'
release    : 30
source     :
    - https://download.gnome.org/sources/vte/0.60/vte-0.60.0.tar.xz : 72d1955eb40b4475b858892813a79545cee34409bac2af470606fb4b4d193a1b
license    : GPL-2.0-or-later
component  : desktop.library
summary    : The VTE package contains a termcap file implementation for terminal emulators.
description: |
    The VTE package contains a termcap file implementation for terminal emulators.
builddeps  :
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpcre2-8)
    - gperf
    - gtk-doc
    - libiconv-devel
    - vala
rundeps    :
    - devel :
        - pcre2-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-build-Add-no-exceptions-sanity-check.patch
    %patch -p1 < $pkgfiles/vte291-cntnr-precmd-preexec-scroll.patch
    %meson_configure -Ddocs=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
