name        : libvte
version     : 0.42.1
release     : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/vte/0.42/vte-0.42.1.tar.xz : 9e00e2e9e94f4202b979c871f407a8815890bc0f4a8448a08534f76ab0fc9d34
license     : GPL-2.0+
summary     : The VTE package contains a termcap file implementation for terminal emulators.
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gnutls)
    - vala
description : |
    The VTE package contains a termcap file implementation for terminal emulators.
setup      : |
    %configure --disable-static \
               --enable-introspection \
               --libexecdir=/usr/lib/vte
build      : |
    %make
install    : |
    %make_install
    mkdir $installdir/usr/share/defaults/
    mv $installdir/etc/ $installdir/usr/share/defaults/
