name        : libvte
version     : 0.40.2
release     : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/vte/0.40/vte-0.40.2.tar.xz : 9b68fbc16b27f2d79e6271f2b0708808594ac5acf979d0fccea118608199fd2d
license     : GPL-2.0+
summary     : The VTE package contains a termcap file implementation for terminal emulators.
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gnutls)
    - vala
description : |
    The VTE package contains a termcap file implementation for terminal emulators.
setup      : |
    %configure --disable-static \
               --enable-introspection \
               --libexecdir=/usr/lib/vte
build      : |
    %make
install    : |
    %make_install
